apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-env
  namespace: applications
  labels:
    app: billing
data:
  BILLING_FREE_TIER_ENABLED: "true"
  BILLING_PUBLIC_PORT: "8084"
  BILLING_GATEWAY_PORT: "8081"
  BILLING_PRIVATE_PORT: "8082"
  BILLING_HEALTH_PORT: "8083"
  BILLING_WEBHOOKS_PORT: "8080"
  BILLING_SHUTDOWN_GRACE_PERIOD: 1m
  BILLING_DB_NAME: billing
  BILLING_DB_HOST: staging.cluster-co4dlqp0oqnh.us-west-2.rds.amazonaws.com
  BILLING_DB_PORT: "5432"
  BILLING_DB_MIGRATIONS_PATH: /usr/share/migrations
  BILLING_SECRETS_ADDR_PRIVATE: server-private.applications.svc.cluster.local:80
  BILLING_COMPUTE_ADDR_PRIVATE: compute.applications.svc.cluster.local:82
  BILLING_EMAIL_ADDR_PRIVATE: email.applications.svc.cluster.local:82
  BILLING_STRIPE_CUSTOMER_PORTAL_URL: https://billing.stripe.com/p/login/test_6oEbLD2n1dXS9nq8ww
  BILLING_CI_HOST_NAME: cloud.staging.earthly.dev
  BILLING_SUPPORT_EMAIL_ADDRESS: support-test+billing@earthly.dev
  BILLING_STRIPE_FREE_TIER_PRICE_ID: price_1NIZijCH3iDXEIBS98fjAt3l
  BILLING_STRIPE_STARTER_TIER_PRICE_ID: price_1NKgIxCH3iDXEIBSp0UKDHMg
  BILLING_STRIPE_PRO_TIER_PRICE_ID: price_1NKgv4CH3iDXEIBSvaF4ZRr6
  BILLING_STRIPE_TEAM_TIER_PRICE_ID: price_1NKh0bCH3iDXEIBSHlUHEGul
  BILLING_STRIPE_STARTER_TIER_YEARLY_PRICE_ID: price_1NPo3eCH3iDXEIBSSFhgSUwZ
  BILLING_STRIPE_PRO_TIER_YEARLY_PRICE_ID: price_1NPoZbCH3iDXEIBSaZ37aKbc
  BILLING_STRIPE_TEAM_TIER_YEARLY_PRICE_ID: price_1NPokFCH3iDXEIBST56LGZOU
  LOG_LEVEL: debug
