apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  namespace: applications
  labels:
    app: billing
spec:
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      namespace: applications
      labels:
        app: billing
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
    spec:
      serviceAccountName: serviceaccount-billing
      terminationGracePeriodSeconds: 300
      imagePullSecrets:
        - name: dockerhub
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - builder
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
      containers:
        - name: billing
          image: earthly/billing:1907.bfefb2b4.nacho_billing_outgoing-reqid
          resources:
            requests:
              memory: 256Mi
              cpu: 300m
            limits:
              memory: 512Mi
              cpu: 1000m
          envFrom:
            - configMapRef:
                name: billing-env
            - secretRef:
                name: billing-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            timeoutSeconds: 1
            failureThreshold: 1
            successThreshold: 3
            periodSeconds: 5
